### ISSUE TITLE
Provide a slider and a percentage that allows to search for specific code age

### ISSUE THREAD

**Issue by RalfKoban** [ATrefzer/Insight#11]
For the Code Age map I would like to have a slider that allows me to define the range I want to see; in addition to the percentage of code that falls in that range.

Example:
I want to see the code that is less than 30 days old.
I also want to see that it is eg. 17% of the overall code base.

**Comment by ATrefzer** [comment]
Implemented without the percentage. The slider is in the Tool window. If you additionally click the checkbox "No filtering, only highlight" the content of the map stays the same but the  files with the selected age are highlighted.
